#!/bin/sh

# 设置语言
uci set luci.main.lang=zh_cn
uci commit luci

# 设置时区
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

# 解决 daemon.err nlbwmon[2083]: Netlink receive failure: Out of memory
sed -i '/net.core.rmem_max/d' /etc/sysctl.conf
echo 'net.core.rmem_max=524288' >> /etc/sysctl.conf
sed -i '/net.core.rmem_default/d' /etc/sysctl.conf
echo 'net.core.rmem_default=524288' >> /etc/sysctl.conf
sysctl -p
uci set nlbwmon.@nlbwmon[0].database_limit=5000
uci commit nlbwmon

# 设置 ttyd 启用 ssl
uci set ttyd.@ttyd[0].ssl=1
uci set ttyd.@ttyd[0].ssl_cert=/etc/nginx/conf.d/_lan.crt
uci set ttyd.@ttyd[0].ssl_key=/etc/nginx/conf.d/_lan.key
uci commit ttyd

# 设置 OpenWrt 相关信息
sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='Official'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release

# 减少 dnsmasq 的 log 输出
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
